services:
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: bookmate
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
